Repository TikitakaDiary/MemoryTrace-Server, pull requests merged in 2021-07, with the labels that each got.

#128 [FEAT] 다이어리 수정 API 추가 (#126)
  src/main/java/com/memorytrace/common/ResponseMessage.java
  src/main/java/com/memorytrace/controller/DiaryController.java
  src/main/java/com/memorytrace/domain/Diary.java
  src/main/java/com/memorytrace/dto/request/DiaryUpdateRequestDto.java
  src/main/java/com/memorytrace/service/DiaryService.java
Labels: enhancement

#151 [FIX] 회원 탈퇴 시 FCM 토큰 삭제 추가 (#144)
  src/main/java/com/memorytrace/controller/FcmController.java
  src/main/java/com/memorytrace/controller/UserController.java
  src/main/java/com/memorytrace/repository/FcmTokenRepository.java
  src/main/java/com/memorytrace/service/FcmService.java
Labels: enhancement

#161 [FIX] token list null 처리 (#160)
  src/main/java/com/memorytrace/service/FirebaseMessagingService.java
Labels: bug

#162 Main Merge
  src/main/java/com/memorytrace/service/FirebaseMessagingService.java
  src/main/java/com/memorytrace/service/UserService.java
Labels: bug

#166 [FIX] 기존 FCM Token API 중복체크 로직 추가 (#165)
  src/main/java/com/memorytrace/controller/UserController.java
  src/main/java/com/memorytrace/service/UserService.java
Labels: bug

#168 [FIX] 기존 회원 재로그인시 토큰 중복 저장되는 부분 수정 (#167)
  src/main/java/com/memorytrace/service/UserService.java
Labels: bug

#171 [FIX] 오류 형식 변경 (#170)
  src/main/java/com/memorytrace/service/UserService.java
Labels: bug

#173 [FIX] 토큰이 없을 때 return 처리 변경 (#172)
  src/main/java/com/memorytrace/service/FirebaseMessagingService.java
Labels: bug

#183 [FIX] 토큰 관련 API 로직 수정 (#180)
  src/main/java/com/memorytrace/config/WebSecurityConfig.java
  src/main/java/com/memorytrace/controller/FcmController.java
  src/main/java/com/memorytrace/dto/request/FcmDeleteRequestDto.java
  src/main/java/com/memorytrace/service/FcmService.java
  src/main/java/com/memorytrace/service/FirebaseMessagingService.java
Labels: bug, documentation

#186 [FIX] 토큰 관련 API 로직 수정 (#185)
  src/main/java/com/memorytrace/service/FirebaseMessagingService.java
Labels: bug

#192 [FIX] 기존 회원 로그인 시 새로운 token 저장 안되는 이슈 (#191)
  src/main/java/com/memorytrace/service/UserService.java
Labels: bug

#195 [FIX] 혼자쓰는 일기장에도 알림이 오는 이슈 (#194)
  src/main/java/com/memorytrace/service/DiaryService.java
Labels: bug

#198 [FIX] 교환일기장 / 일기장 리스트 이슈 (#197)
  src/main/java/com/memorytrace/dto/request/PageRequestDto.java
  src/main/java/com/memorytrace/service/DiaryService.java
Labels: bug

#204 [FIX] 교환일기장 / 일기장 리스트 이슈 (#197)
  src/main/java/com/memorytrace/controller/DiaryController.java
Labels: bug
