Repository TikitakaDiary/MemoryTrace-Server, pull requests merged in 2021-05, with the labels that each got.

#21 Book에 sticker_img 추가
  src/main/java/com/memorytrace/domain/Book.java
  src/main/java/com/memorytrace/dto/request/BookSaveRequestDto.java
  src/main/java/com/memorytrace/dto/response/BookListResponseDto.java
Labels: enhancement

#23 Diary List Read API 추가
  src/main/java/com/memorytrace/controller/DiaryController.java
  src/main/java/com/memorytrace/domain/Book.java
  src/main/java/com/memorytrace/domain/Diary.java
  src/main/java/com/memorytrace/dto/request/DiarySaveRequestDto.java
  src/main/java/com/memorytrace/dto/response/BookListResponseDto.java
  src/main/java/com/memorytrace/dto/response/DiaryDetailResponseDto.java
  src/main/java/com/memorytrace/dto/response/DiaryListResponseDto.java
  src/main/java/com/memorytrace/repository/BookRepository.java
  src/main/java/com/memorytrace/repository/DiaryRepository.java
  src/main/java/com/memorytrace/service/DiaryService.java
Labels: enhancement

#31 [FIX] Diary 생성 API Response 변경, 로직 수정
  src/main/java/com/memorytrace/controller/DiaryController.java
  src/main/java/com/memorytrace/domain/Book.java
  src/main/java/com/memorytrace/service/DiaryService.java
Labels: enhancement

#32 Diary API 수정
  src/main/java/com/memorytrace/controller/DiaryController.java
  src/main/java/com/memorytrace/dto/response/DiaryListResponseDto.java
  src/main/java/com/memorytrace/service/DiaryService.java
Labels: enhancement

#39 [FIX] Invite Response 수정
  src/main/java/com/memorytrace/controller/DiaryController.java
  src/main/java/com/memorytrace/dto/response/DiarySaveResponseDto.java
  src/main/java/com/memorytrace/service/DiaryService.java
Labels: enhancement

#43 Diary List 조회 API에 title 추가
  src/main/java/com/memorytrace/dto/response/DiaryListResponseDto.java
  src/main/java/com/memorytrace/service/DiaryService.java
Labels: enhancement

#47 [FEAT] Book List Paging 처리(#46)
  src/main/java/com/memorytrace/controller/BookController.java
  src/main/java/com/memorytrace/dto/request/PageRequestDto.java
  src/main/java/com/memorytrace/dto/response/BookListResponseDto.java
  src/main/java/com/memorytrace/dto/response/PageResponseDto.java
  src/main/java/com/memorytrace/repository/UserBookRepository.java
  src/main/java/com/memorytrace/service/BookService.java
  src/main/java/com/memorytrace/service/DiaryService.java
Labels: enhancement

#52 [DOCS] Swagger API 설명 변경(#51)
  src/main/java/com/memorytrace/controller/BookController.java
  src/main/java/com/memorytrace/controller/DiaryController.java
  src/main/java/com/memorytrace/controller/InviteController.java
  src/main/java/com/memorytrace/controller/UserController.java
  src/main/java/com/memorytrace/dto/request/DiarySaveRequestDto.java
Labels: documentation, enhancement

#58 [DOCS] Swagger description 추가(#57)
  src/main/java/com/memorytrace/domain/DefaultRes.java
  src/main/java/com/memorytrace/dto/request/BookSaveRequestDto.java
  src/main/java/com/memorytrace/dto/request/DiarySaveRequestDto.java
  src/main/java/com/memorytrace/dto/response/BookDetailResponseDto.java
  src/main/java/com/memorytrace/dto/response/BookListResponseDto.java
  src/main/java/com/memorytrace/dto/response/BookSaveResponseDto.java
  src/main/java/com/memorytrace/dto/response/DiaryDetailResponseDto.java
  src/main/java/com/memorytrace/dto/response/DiaryListResponseDto.java
  src/main/java/com/memorytrace/dto/response/DiarySaveResponseDto.java
  src/main/java/com/memorytrace/dto/response/PageResponseDto.java
  src/main/java/com/memorytrace/dto/response/UserDetailResponseDto.java
Labels: documentation

#79 [FIX] Swagger model 응답 값 다른 이슈 #78
  src/main/java/com/memorytrace/controller/BookController.java
  src/main/java/com/memorytrace/controller/DiaryController.java
  src/main/java/com/memorytrace/controller/InviteController.java
  src/main/java/com/memorytrace/controller/UserController.java
  src/main/java/com/memorytrace/dto/response/BookDetailResponseDto.java
  src/main/java/com/memorytrace/dto/response/BookListResponseDto.java
Labels: bug

#82 [FIX] User Create Api RequestBody로 변경
  src/main/java/com/memorytrace/controller/UserController.java
  src/main/java/com/memorytrace/dto/request/UserSaveRequestDto.java
  src/main/java/com/memorytrace/service/UserService.java
Labels: enhancement

#86 [FEAT] 05.22 회의 건 API (#83)
  src/main/java/com/memorytrace/common/ResponseMessage.java
  src/main/java/com/memorytrace/common/StatusCode.java
  src/main/java/com/memorytrace/controller/BookController.java
  src/main/java/com/memorytrace/domain/BaseTimeEntity.java
  src/main/java/com/memorytrace/domain/Book.java
  src/main/java/com/memorytrace/dto/request/BookUpdateRequestDto.java
  src/main/java/com/memorytrace/dto/request/InviteSaveRequestDto.java
  src/main/java/com/memorytrace/dto/response/BookDetailResponseDto.java
  src/main/java/com/memorytrace/dto/response/BookListResponseDto.java
  src/main/java/com/memorytrace/dto/response/DiaryDetailResponseDto.java
  src/main/java/com/memorytrace/dto/response/DiaryListResponseDto.java
  src/main/java/com/memorytrace/repository/BookRepository.java
  src/main/java/com/memorytrace/service/BookService.java
  src/main/java/com/memorytrace/service/DiaryService.java
Labels: enhancement

#90 [STYLE] User 관련 Request, Response 변경 (#89)
  src/main/java/com/memorytrace/dto/request/UserSaveRequestDto.java
  src/main/java/com/memorytrace/dto/response/UserDetailResponseDto.java
Labels: enhancement
